config/routes.rb
Rails.application.routes.draw do
  get 'map/index'

  resources :points

end

app/models/point.rb
class Point < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @point_start = Point.find(1)
     @point_goal = Point.find(2)
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.all
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_params
      params.require(:point).permit(:title, :address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mapvavi</title>
  <!-- <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script> -->
+  <script src="//maps.google.com/maps/api/js?v=3&key="<%= Rails.application.secrets.google_map_key %>></script>
 +  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
 +  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/map/index.html.erb
<h1>地図ページ</h1>
  <div id="map" style='width: 800px; height: 800px;'></div>
</div>

<script type="text/javascript">
var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();

function calcRoute() {
  var origin      = new google.maps.LatLng(<%= @point_start.latitude %>,<%= @point_start.longitude %>);
  var destination = new google.maps.LatLng(<%= @point_goal.latitude %>,<%= @point_goal.longitude %>);
  var request = {
      origin:      origin,
      destination: destination,
      travelMode:  google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    }
  });
}

calcRoute();

    var handler = Gmaps.build('Google');
handler.buildMap({ provider: {
  mapTypeId: google.maps.MapTypeId.DRIVING
  },internal: {id: 'map'}}, function(){
  directionsDisplay.setMap(handler.getMap());
    });

</script>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing Point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Points</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @points.each do |point| %>
      <tr>
        <td><%= point.title %></td>
        <td><%= point.address %></td>
        <td><%= point.latitude %></td>
        <td><%= point.longitude %></td>
        <td><%= link_to 'Show', point %></td>
        <td><%= link_to 'Edit', edit_point_path(point) %></td>
        <td><%= link_to 'Destroy', point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point', new_point_path %>

app/views/points/new.html.erb
<h1>New Point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @point.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= @point.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @point.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @point.longitude %>
</p>

<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %>